ChatApp.Web/ChatApp.Web/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChatApp.Web.BL;
using ChatApp.Web.Models;

namespace ChatApp.Web.Controllers
{
    public class MediaController : Controller
    {
        //
        // GET: /Media/

        public PartialViewResult Index()
        {
			return PartialView();
        }

		public ActionResult Audio()
		{
			return View(Utils.GetYoutubeDataViewModel());
		}

        public PartialViewResult PhotoViewer()
        {
            return PartialView(MediaBI.GetPhotoSets());
        }

        public JsonResult ListPhotosets()
        {
            return Json(MediaBI.GetPhotoSets(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPhotoset(string setID)
        {
            return Json(MediaBI.GetPhotoSet(setID), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAllPhotosInSet(string setID)
        {
            return Json(MediaBI.GetPhotosInSet(setID),JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPhotosInSet(string setID,int page)
        {
            return Json(MediaBI.GetPhotosInSet(setID, page), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPhotoInfo(string photoID)
        {
            return Json(MediaBI.GetPhotoInfo(photoID), JsonRequestBehavior.AllowGet);
        }
    }
}

ChatApp.Web/ChatApp.Web/Views/Shared/Caocao.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title></title>
</head>
<body>
	<div style="width:100vw;height:100vh;">
		<div id="game-container" style="text-align:center">
			<iframe src="@Url.Action("testp","test")"
					style="width:960px;height:600px;margin:0 auto;overflow:hidden"
					scrolling="no" seamless="seamless" align="middle"></iframe>
		</div>
	</div>
</body>
</html>

ChatApp.Web/ChatApp.Web/Views/Shared/Phaser.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
	<script src="~/Content/Scripts/Queue.js"></script>
	<script src="~/Content/Scripts/Games/phaser.js"></script>
	<script src="~/Content/Scripts/Games/PhaserTest/Game.js"></script>
</head>
<body>
		<script type="text/javascript">

		window.onload = function ()
		{

			var game = new MainGame();
			game.init(window.innerWidth, window.innerHeight);
		};

		document.addEventListener("contextmenu", function (e)
		{
			e.preventDefault();
			console.log(e);
		});
		</script>
</body>
</html>

ChatApp.Web/ChatApp.Web/Views/Shared/ThreeTest.cshtml
@{
    ViewBag.Title = "ThreeTest";
}
<style>
    body {
        margin: 0;
    }

    canvas {
        width: 100%;
        height: 100%;
    }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r70/three.js"></script>
<script src="~/Content/Scripts/Games/ThreeTest/Detector.js"></script>
<script src="~/Content/Scripts/Games/ThreeTest/KeyboardState.js"></script>
<script src="~/Content/Scripts/Games/ThreeTest/THREEx.FullScreen.js"></script>
<script src="~/Content/Scripts/Games/ThreeTest/THREEx.WindowResize.js"></script>
<script src="~/Content/Scripts/Games/ThreeTest/Projector.js"></script>
<script src="~/Content/Scripts/Games/ThreeTest/CameraController.js"></script>
<script src="~/Content/Scripts/Games/ThreeTest/Game.js"></script>
<div id="ThreeJS" style="position: absolute; left:0; top:0;"></div>
<script>
	var g = new Game("ThreeJS");
</script>

ChatApp.Web/ChatApp.Web/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script type="text/javascript" src="~/Content/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript" src="~/Content/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/Content/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

ChatApp.Web/ChatApp.Web/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCo-q1vlh3Koh9g8cauTwE_x4Va68bMelo"></script>
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.0/masonry.pkgd.js"></script>
    <script type="text/javascript" src="~/Content/Scripts/PhotoViewer/imagesloaded.pkgd.js"></script>
    <script type="text/javascript" src="~/Content/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript" src="~/Content/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript" src="~/Content/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script type="text/javascript" src="~/Content/Scripts/Player.js"></script>
    <script type="text/javascript" src="~/Content/Scripts/PhotoViewer.js"></script>
	<script type="text/javascript" src="~/Content/Scripts/PhotoViewer/glisse.js"></script>
	<script type="text/javascript" src="~/Content/Scripts/Layout.js"></script>
	<link rel="stylesheet" type="text/css" href="~/Content/CSS/glisse.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/CSS/Site.css" />
    <link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/CSS/PhotoViewer.css" />
</head>
<body>
    <div class="whole-page">
        <div>
            @{Html.RenderPartial("_UpperBar");}
        </div>
        <div>
            @{Html.RenderPartial("_NavMenu");}
        </div>
        <div id="mainContentContainer">
            @RenderSection("mainContent")
        </div>
        <footer></footer>
    </div>
    <div id="overlay">
        @*<div>
                <img src="~/Content/Images/loading-blue.gif" />
                <button value="close" onclick="overlay();">Close</button>
            </div>*@
        <div>
            @*<img src="~/Content/Images/loading-black.gif" />*@
            <img src="~/Content/CSS/images/loader.gif" />
        </div>
    </div>
</body>
</html>

ChatApp.Web/ChatApp.Web/Views/Shared/_MediaLayout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
	<link rel="stylesheet" type="text/css" href="~/Content/CSS/Media.css" />
	<script type="text/javascript" src="~/Content/Scripts/prefixfree.min.js"></script>
</head>
<body>
	<div id="mainContainer">
		<div id="upper"></div>
		<div id="center">
			<div id="centerContainer">
				<div id="center-left">
					<h3>Playlists:</h3>
				</div>
				<div id="center-center"></div>
				<div id="center-right">
					<h3>Videos:</h3>
				</div>
			</div>
		</div>
		<div id="bottom"></div>
	</div>
</body>
</html>

ChatApp.Web/ChatApp.Web/Views/Shared/_NavMenu.cshtml
<div id="NavMenu">
    <ul id="menu">
        <li data-postloadaction="__goHome" data-wholepage="true">Home</li>
        <li data-url="@Url.Action("CurrentLocation","Location")" data-postLoadAction="initialize">Where am I</li>
        <li data-url="@Url.Action("Index","Home")">Media Gallery</li>
        <li data-url="@Url.Action("Index","Home")">Other Resources</li>
		<li data-url="@Url.Action("Register","Account")">Register</li>
		<li data-url="@Url.Action("Login","Account")">Login</li>
		<li onclick="overlay();">overlay</li>
		<li data-url="@Url.Action("Index", "Media")" data-postloadaction="initializePlayer">Media</li>
        <li data-url="@Url.Action("PhotoViewer","Media")">PhotoViewer</li>
    </ul>
</div>

<script type="text/javascript">
    function __goHome() {
        var home = "@Url.Action("Index", "Home")";
    	window.location = home;
    }
</script>

ChatApp.Web/ChatApp.Web/Views/Shared/_UpperBar.cshtml
<div id="UpperBarContainer">
	<div id="ubLeft">

	</div>
	<div id="ubCenter">

	</div>
	<div id="ubRight">
		@{
			if (null != HttpContext.Current.User && null != HttpContext.Current.User.Identity && !string.IsNullOrWhiteSpace(HttpContext.Current.User.Identity.Name))
			{
				<span>Welcome @Html.ActionLink(HttpContext.Current.User.Identity.Name, "ProfileDetail", "Account")</span>
				<span>|</span>
				<span>@Html.ActionLink("Log out","Logout","Account")</span>
			}
			else
			{
				<span>@Html.ActionLink("Log in","Index","Account")</span>
				<span>|</span>
				<span>@Html.ActionLink("Sign up","Signup","Account")</span>
			}
		}
	</div>
</div>

ChatApp.Web/ChatApp.Web/Views/Shared/_baoziLayout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
	<script type="text/javascript" src="~/Content/Scripts/baozi.js"></script>	
	<link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
	<link rel="stylesheet" type="text/css" href="~/Content/CSS/Baozi.css" />
	<script type="text/javascript" src="~/Content/Scripts/prefixfree.min.js"></script>
</head>
<body>
	<div>
		@RenderBody()
	</div>
</body>
</html>